### ISSUE TITLE
lua mod api support

### ISSUE THREAD

**Issue by Pevernow** [BuleStorm/Cpp-OpenGL-Imitate-Minecraft#2]
让该项目支持动态语言编写的mod。
提供luajit2.0.5
并添加钩子

**Comment by BuleStorm** [comment]
懵逼问号脸，又是一个技术点

**Comment by BuleStorm** [comment]
> 让该项目支持动态语言
> 编写的mod。提供luajit2.0.5
> 并添加钩子

懵逼问号脸，又是一个技术点

**Comment by Pevernow** [comment]
我可以提供技术支持.......
玩过mc的对mod都有常识吧

**Comment by Pevernow** [comment]
还有跨平台化，cmake

**Comment by BuleStorm** [comment]
> 还有跨平台化，cmake

私聊
